/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yooho_zerostart_jnicode_JniProxy */

#ifndef _Included_com_example_yooho_zerostart_jnicode_JniProxy
#define _Included_com_example_yooho_zerostart_jnicode_JniProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yooho_zerostart_jnicode_JniProxy
 * Method:    getNativeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yooho_zerostart_jnicode_JniProxy_getNativeString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
